on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.createComment({...context.issue, body: 'Here is your build button: http://jenkins-mch.cscs.ch/job/MeteoSwissAPN-test/job/' + context.issue.repo.name +'/view/change-requests/job/PR-' + context.issue.number +'/build?delay=0sec'})
